version: '3.8'

services:
  # Frontend Application
  frontend:
    image: matias151/schooldev_front:latest
    container_name: schooldev_front
    restart: unless-stopped
    networks:
      - web
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app-schooldev.duckdns.org`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  web:
    name: web
    external: true