version: '3.8'

services:
  # Production Frontend
  frontend-production:
    image: matias151/schooldev_front:latest
    container_name: schooldev_front_production
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - schooldev-network
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-prod.rule=Host(`schooldev.duckdns.org`)"
      - "traefik.http.routers.frontend-prod.tls=true"
      - "traefik.http.services.frontend-prod.loadbalancer.server.port=80"

  # Staging Frontend  
  frontend-staging:
    image: matias151/schooldev_front:staging
    container_name: schooldev_front_staging
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - schooldev-network
    environment:
      - NODE_ENV=staging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-staging.rule=Host(`staging.schooldev.duckdns.org`)"
      - "traefik.http.routers.frontend-staging.tls=true"
      - "traefik.http.services.frontend-staging.loadbalancer.server.port=80"
    profiles:
      - staging

networks:
  schooldev-network:
    external: true