version: '3.8'

services:
  # Frontend Application
  frontend:
    image: matias151/schooldev_front:latest
    container_name: schooldev_front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - schooldev-network
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`schooldev.duckdns.org`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  schooldev-network:
    external: true